"""Temporary file storage: one directory per upload, removed after the retention period."""

import json
import re
import shutil
import time
import uuid
from pathlib import Path

FILE_ID_RE = re.compile(r"^[0-9a-f]{32}$")

ORIGINAL_NAME = "original"
THUMBNAIL_NAME = "thumbnail.png"
META_NAME = "meta.json"


class Storage:
    def __init__(self, root: Path, retention_seconds: int):
        self.root = root
        self.retention_seconds = retention_seconds
        self.root.mkdir(parents=True, exist_ok=True)

    def _dir(self, file_id: str) -> Path | None:
        # Ids are generated by the service; anything else is treated as unknown,
        # so a client-supplied id can never point outside the storage root.
        if not FILE_ID_RE.fullmatch(file_id):
            return None
        return self.root / file_id

    def save(self, original: bytes, thumbnail_png: bytes, meta: dict) -> dict:
        file_id = uuid.uuid4().hex
        target = self.root / file_id
        target.mkdir()  # fails if the directory already exists, so nothing is overwritten
        now = time.time()
        meta = {**meta, "id": file_id, "created_at": now, "expires_at": now + self.retention_seconds}
        (target / ORIGINAL_NAME).write_bytes(original)
        (target / THUMBNAIL_NAME).write_bytes(thumbnail_png)
        (target / META_NAME).write_text(json.dumps(meta))
        return meta

    def get_meta(self, file_id: str) -> dict | None:
        target = self._dir(file_id)
        if target is None or not (target / META_NAME).is_file():
            return None
        meta = json.loads((target / META_NAME).read_text())
        if meta["expires_at"] <= time.time():
            self.delete(file_id)
            return None
        return meta

    def thumbnail_path(self, file_id: str) -> Path | None:
        if self.get_meta(file_id) is None:
            return None
        return self.root / file_id / THUMBNAIL_NAME

    def delete(self, file_id: str) -> bool:
        target = self._dir(file_id)
        if target is None or not target.is_dir():
            return False
        shutil.rmtree(target)
        return True

    def cleanup_expired(self) -> int:
        removed = 0
        now = time.time()
        for entry in self.root.iterdir():
            meta_file = entry / META_NAME
            try:
                expires_at = json.loads(meta_file.read_text())["expires_at"]
            except (OSError, ValueError, KeyError):
                continue
            if expires_at <= now:
                shutil.rmtree(entry, ignore_errors=True)
                removed += 1
        return removed
